config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :communes, only: [:index], path: '/results' do
    get :geojson, on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commune.rb
class Commune < ApplicationRecord
  has_many :gares
  has_many :ecoles
  has_many :pharmacies
end

app/models/ecole.rb
class Ecole < ApplicationRecord
  belongs_to :commune
end

app/models/gare.rb
class Gare < ApplicationRecord
  belongs_to :commune
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  belongs_to :commune
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/communes_controller.rb
class CommunesController < ApplicationController
  def index
    @gares = Gare.all
    @gare_markers = @gares.map do |gare|
      {
        lat: gare.latitude,
        lng: gare.longitude,
        image_url: helpers.asset_url('train.png')
      }
    end
  end

  def geojson
    communes = display_commune
    @communes = distance_bet(communes)
    features = @communes.map do |commune|
      {
        'type': 'Feature',
        'geometry': {
          'type': 'Polygon',
          'coordinates': commune.polygon
        },
        'properties': {
          'description': "<h4>#{commune.name.capitalize}</h4>
                          <div class='pop-flex'>
                            <h5>Prix €/m²</h5>
                            <p>#{commune.price.to_i}</p>
                          </div>
                          <div class='pop-flex'>
                            <h5>Gares</h5>
                            <p>#{commune.gares.count}</p>
                          </div>
                          <div class='pop-flex'>
                            <h5>Ecoles</h5>
                            <p>#{commune.ecoles.count}</p>
                          </div>
                          <div class='pop-flex'>
                          <h5>Pharmacies</h5>
                          <p>#{commune.pharmacies.count}</p>
                          </div>",
          'color': color_get(commune)
        }
      }
    end


    json = {
      "type": "FeatureCollection",
      "features": features
    }

    render json: json
  end

  private

  def display_commune
    @communes = Commune.all
    max_price = params[:price_query].to_f * 1.10
    @communes = @communes.where('price <= ?', max_price) if params[:price_query].present?
    return @communes
  end

  def distance_bet(communes)
    final_communes = []
    distance = params[:distance].to_f
    lat = params[:lat].to_f
    long = params[:long].to_f
    center = [long, lat]
    communes.each do |commune|
      commune_center = [commune.longitude, commune.latitude]
      if Geocoder::Calculations.to_kilometers(Geocoder::Calculations.distance_between(center, commune_center)) <= distance
        final_communes << commune
      end
    end
    final_communes
  end

  def coordonnes_display(communes)
    coordonnes = []
    communes.each do |commune|
      coordonnes << commune.polygon[0]
    end
    coordonnes
  end

  def color_get(commune)
    max_price = params[:price_query].to_f * 1.10
    price = commune.price
    if price / max_price >= 0.98
      return '#e6a13d'
        # doit retourner '#FFB344', mais n'affiche rien
        # la couleur est à matcher avec la variable SCSS $echo dans _colors.scss
    elsif price / max_price <= 0.88
      return '#58a4b7'
        # la couleur est à matcher avec la variable SCSS $charlie dans _colors.scss
    else
      return '#00726e'
        # la couleur est à matcher avec la variable SCSS $delta dans _colors.scss
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @communes = Commune.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/communes/index.html.erb
<%
  min = (params[:price_query].to_i * 1.1 * 0.88).round(-1)
  mid = (params[:price_query].to_i * 1.1 * 0.98).round(-1)
  max = (params[:price_query].to_i * 1.1).round(-1)

  legends = [
    {
      color: '#e6a13d',
      # la couleur est à matcher avec la variable SCSS $charlie dans _colors.scss
      label: "Entre <span data-legend-target=\"mid\">#{mid}</span> et <span data-legend-target=\"max\">#{max}</span> €/m²".html_safe,
      description: ""
    },
    {
      color: '#00726e',
      # la couleur est à matcher avec la variable SCSS $echo dans _colors.scss
      label: "Entre <span data-legend-target=\"min\">#{min}</span> et <span data-legend-target=\"mid\">#{mid}</span> €/m²".html_safe,
      description: ""
    },
    {
      color: '#58a4b7',
      # la couleur est à matcher avec la variable SCSS $delta dans _colors.scss
      label: "En dessous de <span data-legend-target=\"min\">#{min}</span> €/m²".html_safe,
      description: ""
    }
  ]
%>


<main data-controller="legend">
  <div class="results"
       data-controller="box"
       data-box-lat-value="<%= params[:lat] %>"
       data-box-long-value="<%= params[:long] %>"
       data-box-distance-value="<%= params[:km] %>"
       data-box-address-value="<%= params[:address] %>"
       data-box-gare-active-value="<%= false %>"
       data-box-gare-marker-value="<%= @gare_markers.to_json %>">

    <div class="card-criteres">
      <div class="hero-index">
        <%= link_to "MappyRhône", root_path %>
      </div>

      <div class="search-form card" data-controller="geocoder">
        <div class="card-body from-group p-4">
          <%= form_with url: communes_path, method: :get do |f| %>
            <div class="label my-2">
              <%= f.label :address, "Lieu de travail", class: "label-description p-2" %>
              <%= f.text_field :address,
                                placeholder: 'Entrez une adresse',
                                value: params[:address],
                                id: 'geo-address',
                                data: {
                                        box_target: "addressInput",
                                        action: "latlngChange->box#updateAddress"
                                      },
                                class:"form-control p-3" %>
            </div>
            <div class="label my-2" data-controller="price">
                <%= f.label :price, 'Surface en m² souhaitée?', class: "label-description p-2" %>
                <%= f.text_field :metre_query,
                                 class:"form-control my-2",
                                 placeholder: 'Entrez votre surface en m²',
                                 data: {
                                         price_target: "metre",
                                         action: "keyup->price#calcul"
                                       },
                                 value: params[:metre_query]%>
                <%= f.label :price, 'Votre budget', class: "label-description p-2" %>
                <%= f.text_field :budget_query,
                                 class:"form-control mb-2",
                                 placeholder: 'Entrez votre budget en euros',
                                 data: {
                                         price_target: "budget",
                                         action: "keyup->price#calcul"
                                       },
                                 value: params[:budget_query] %>
                <%= f.label :price, 'Prix au m² correspondant', class: "label-description p-2" %>
                <%= f.text_field :price_query,
                                 class:"form-control",
                                 disabled: true,
                                 data: {
                                         price_target: "price",
                                         box_target: "priceInput",
                                         legend_target: 'range',
                                         action: 'input->box#fetchGeoJson input->legend#updateRange'
                                       },
                                 value: params[:price_query] %>
            </div>
            <div class="label my-2" data-controller="slider">
              <%= f.label :km, 'Distance souhaitée en km', class: "label-description p-2" %>
              <div class="d-flex align-items-center">
                <%= f.range_field :km,
                                  in: 0..50 ,
                                  class:"form-range p-3",
                                  min:"0",
                                  max:"50",
                                  step:"2",
                                  data: {
                                          slider_target: "cursor",
                                          box_target: "distanceInput",
                                          action: "mousemove->slider#slide input->box#fetchGeoJson"
                                        },
                                  value: params[:km] %>
                <span class="kilometers text-secondary fw-bold" data-slider-target="range"></span>
              </div>
            </div>
          <% end %>

          <%= form_with do |f| %>
            <div class="form-check form-switch pt-4 switch-block" >
              <div>
                <%= f.label :gare, "Afficher les gares",for: "toggler", class: "form-check-label label-description-text" %>
              </div>
              <div>
                <%= f.check_box :gare, {
                                         id: 'toggler',
                                         class: "form-check-input",
                                         checked: false,
                                         data: { action: "click->box#toggleGares" }
                                       }, '0' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="right-section">

      <div class="animation" data-controller="animation" data-animation-target="animated">
        <div class="wrapper">
          <div class="static-txt">Chargement des</div> <!--  Texte à changer + ajouter un peu de time + afffinage des résultats -->
          <ul class="dynamic-txt">
            <li><span class="vert">communes</span></li>
            <li><span class="bleu">gares</span></li>
            <li><span class="jaune">écoles</span></li>
          </ul>
        </div>
      </div>

      <div class="mapbox" data-box-target="mapContainer">
        <div class="card-legend">
          <% legends.each do |legend| %>
            <div style="background: <%= legend[:color] %>; width: 30px; height: 20px; "></div>
              <div class="text">
                <p class="title"><%= legend[:label] %></p>
                <p class="description"><%= legend[:description] %></p>
              </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <!-- Hotjar Tracking Code for my site -->
    <script>
      (function(h,o,t,j,a,r){
          h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
          h._hjSettings={hjid:2890117,hjsv:6};
          a=o.getElementsByTagName('head')[0];
          r=o.createElement('script');r.async=1;
          r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
          a.appendChild(r);
      })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>

<section class="section-hero">
  <div class="hero container">
    <div class="hero-title text-light">
      <h1 class="title">Une seule <span class="highlight">recherche</span> pour <span class="highlight">investir</span></h1>
      <p> Un projet d'<span class="highlight">achat</span> immobilier ? Visualisez les <span class="highlight">communes</span> et arrondissements en fonction de votre <span class="highlight">budget</span> et de votre lieu de <span class="highlight">travail</span> sur le Rhône.</p>
      <p> MappyRhône est une solution <span class="highlight">gratuite</span>.</p>
    </div>

    <div class="hero-image">
      <div class="search-form card " style="width:600px">
        <div class="card-body from-group p-4">
          <h2 class="card-title text-center border-bottom pb-2 mb-2">Recherchez maintenant</h2>
          <%= form_with url: communes_path, method: :get do |f| %>
           <div class="label my-2" data-controller="geocoder">
              <%= f.label :address, "Lieu de travail", class: "label-description p-2" %>
              <%= f.text_field :address,
                                placeholder: 'Entrez une adresse',
                                value: params[:address],
                                id: 'geo-address',
                                class:"form-control p-3" %>

              <%= f.hidden_field :lat, id: 'geo-lat' %>
              <%= f.hidden_field :long, id: 'geo-long' %>
           </div>
           <div class="label my-2" data-controller="price">
              <%= f.label :price, 'Surface', class: "label-description p-2" %>
              <%= f.text_field :metre_query,
                               class:"form-control mb-2",
                               placeholder: 'Entrez votre surface en m²',
                               data: {
                                       price_target: "metre",
                                       action: "keyup->price#calcul"
                                     }%>
              <%= f.label :price, 'Votre budget', class: "label-description p-2" %>
              <%= f.text_field :budget_query,
                               class:"form-control mb-2",
                               placeholder: 'Entrez votre budget en euros',
                               data: {
                                       price_target: "budget",
                                       action: "keyup->price#calcul"
                                     } %>
              <%= f.label :price, 'Prix au m² correspondant', class: "label-description p-2" %>
              <%= f.text_field :price_query,
                               class:"form-control",

                               data: { price_target: "price" } %>
           </div>
           <div class="label my-2" data-controller="slider">
              <%= f.label :km, 'Distance souhaitée en kilomètres', class: "label-description p-2" %>
              <div class="d-flex align-items-center">
                <%= f.range_field :km,
                                  in: 0..50,
                                  class:"form-range p-3",
                                  min:"0",
                                  max:"50",
                                  step:"2",
                                  data: {
                                          slider_target: "cursor",
                                          action: "mousemove->slider#slide"
                                        } %>
                <span class="kilometers text-secondary fw-bold" data-slider-target="range"></span>
              </div>

           </div>
            <%= f.submit "Voir les resultats", class:"btn btn-primary w-100 mt-4 btn-recherche" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<footer class="container d-flex justify-content-between">
  <div class="footer-links">
    <a href="https://github.com/elbto/mappy-rhone"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonlyon/"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="footer-copyright">
    <p class="copyright">Mappy Rhône Inc® Design et création @ Le Wagon Lyon</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "MappyRhône", root_path, class: "navbar-brand logo"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>